### ISSUE TITLE
Bro, is it really lucrative to be a virus?

### ISSUE THREAD

**Issue by BUGOAO** [skidfromdao/Miner-Tool#1]
This is the identical code repository as yours, and it has gone offline. Perhaps it's you, who hacked my computer and demanded ransom. Are you in such a hurry for money? Living off this kind of work is no easy feat. How did you delete your account? Aren't you the one who was brave enough to send me an email? Please, you or your team can reply to me.

![image](https://github.com/skidfromdao/Miner-Tool/assets/46293847/e28b2bab-e95f-4ff2-9b13-cb166cc1ff80)

**Comment by yanyuhualb** [comment]
Brother, I don't know if you can read and write a letter. I want to tell you here that I don't know what you're talking about. I haven't sent viruses to others, and I don't have the ability to write virus programs. You should have the wrong person. I don't know where you got my email, but I'm really not the person you're looking for.



---Original---
From: ***@***.***&gt;
Date: Mon, May 27, 2024 17:44 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [skidfromdao/Miner-Tool] Bro, is it really lucrative to be a virus?(Issue #1)




 
This is the identical code repository as yours, and it has gone offline. Perhaps it's you, who hacked my computer and demanded ransom. Are you in such a hurry for money? Living off this kind of work is no easy feat. How did you delete your account? Aren't you the one who was brave enough to send me an email? Please, you or your team can reply to me.
 
image.png (view on web)
